# Generated by Django 3.0.4 on 2020-04-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contraccion',
            old_name='duración',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='patada',
            old_name='duración',
            new_name='duracion',
        ),
        migrations.RemoveField(
            model_name='patada',
            name='numero',
        ),
        migrations.AddField(
            model_name='patada',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tension',
            name='pulsaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Cita médico', 'Cita médico'), ('Recordatorio', 'Recordatorio'), ('Fecha importante', 'Fecha importante')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Fotografia',
        ),
    ]
