# Generated by Django 3.0.4 on 2020-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_auto_20200427_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='cAbdominal',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medida',
            name='dBiparieta',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='medida',
            name='lFemur',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
