# Generated by Django 3.0.4 on 2020-04-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_auto_20200417_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('Cita médico', 'Cita médico'), ('Recordatorio', 'Recordatorio'), ('Fecha importante', 'Fecha importante')], max_length=100),
        ),
    ]
