# Generated by Django 3.0.4 on 2020-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_auto_20200429_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='cAbdominal',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='medida',
            name='dBiparieta',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='medida',
            name='lFemur',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
