# Generated by Django 3.0.4 on 2020-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_auto_20200429_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiereNot',
            field=models.BooleanField(default=True),
        ),
    ]
