# Generated by Django 3.0.4 on 2020-05-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_user_quierenot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quiereNot',
            field=models.BooleanField(default=False, verbose_name='quiereNot'),
        ),
    ]
