# Generated by Django 3.0.4 on 2020-05-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_auto_20200511_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quiereNot',
            field=models.BooleanField(default=False),
        ),
    ]
